# This is the repository specific custom dictionary
#
# Write the words in alphabetical order, one word per line.
# If an unknown word is generic put it into the global dictionary
# in lib/tasks/spell.yml file.

---
dictionary:
  - CPUs
  # The Yast namespace, the whole tool is spelled YaST!
  - Yast
  - aspell
  - raspell
  - rspec
  - SLE
  # As part of YAST_SUBMIT
  - YAST
