
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Ruby Check
      run: yast-ci-ruby
